[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-bundle-env"
  [plugins.inputs]
    directories = ["src"]
    extensions = ["js", "jsx"]

[[plugins]]
  package = "netlify-plugin-html-validate"
  [plugins.inputs]
    path = "dist"

